/**
 * Pure tree-building functions for converting AXNode → TreeNode → NodeDescriptor.
 * Separated from refresher.ts to avoid side-effect imports (daemon, native-ax) in tests.
 */
import type { AXNode } from "../apps/types.js";
import type { PlainNode } from "../cli/types.js";
import type { NodeDescriptor } from "../crdt/schema.js";

/** JSON tree node shape for the CRDT */
export interface TreeNode {
  id: string;
  tag: string;
  props: Record<string, string>;
  children?: TreeNode[];
}

// --- Subrole → Tag mapping ---
export const SUBROLE_TO_TAG: Record<string, string> = {};

// --- Role → Tag mapping ---
export const ROLE_TO_TAG: Record<string, string> = {
  AXApplication: "Application",
  AXWindow: "Window",
  AXSheet: "Sheet",
  AXDialog: "Dialog",
  AXPopover: "Popover",
  AXToolbar: "Toolbar",
  AXTabGroup: "TabGroup",
  AXSplitGroup: "SplitGroup",
  AXMenuBar: "MenuBar",
  AXMenu: "Menu",
  AXMenuBarItem: "MenuBarItem",
  AXMenuItem: "MenuItem",
  AXTable: "Table",
  AXOutline: "Outline",
  AXList: "List",
  AXRow: "Row",
  AXColumn: "Column",
  AXCell: "Cell",
  AXScrollArea: "ScrollArea",
  AXBrowser: "Browser",
  AXButton: "Button",
  AXPopUpButton: "PopUpButton",
  AXMenuButton: "MenuButton",
  AXComboBox: "ComboBox",
  AXTextField: "TextField",
  AXTextArea: "TextArea",
  AXSearchField: "SearchField",
  AXCheckBox: "CheckBox",
  AXRadioButton: "RadioButton",
  AXRadioGroup: "RadioGroup",
  AXSwitch: "Switch",
  AXLink: "Link",
  AXTab: "Tab",
  AXSlider: "Slider",
  AXIncrementor: "Incrementor",
  AXDisclosureTriangle: "DisclosureTriangle",
  AXColorWell: "ColorWell",
  AXDateField: "DateField",
  AXSegmentedControl: "SegmentedControl",
  AXImage: "Image",
  AXStaticText: "StaticText",
  AXHeading: "Heading",
  AXWebArea: "WebArea",
  AXSplitter: "Splitter",
  AXGroup: "Group",
};

/** Tags that carry semantic meaning; everything else is structural noise to collapse. */
export const SEMANTIC_TAGS = new Set([
  "Application", "Window", "Sheet", "Dialog", "Popover",
  "Toolbar", "TabGroup", "SplitGroup",
  "MenuBar", "Menu", "MenuBarItem", "MenuItem",
  "Table", "Outline", "List", "Row", "Column", "Cell",
  "ScrollArea", "Browser",
  "Button", "PopUpButton", "MenuButton", "ComboBox",
  "TextField", "TextArea", "SearchField",
  "CheckBox", "RadioButton", "RadioGroup", "Switch",
  "Link", "Tab",
  "Slider", "Incrementor",
  "DisclosureTriangle", "ColorWell", "DateField",
  "SegmentedControl",
  "Image",
  "Splitter",
  "ContextMenu", "Separator",
  "StaticText", "Heading",
  "WebArea", "WebApplication",
  "More",
]);

/** Detect menu separator: AXMenuItem with no title/label/value and tiny height,
 *  or explicit AXSeparatorMenuItem subrole. */
export function isMenuSeparator(ax: AXNode): boolean {
  if (ax.role !== "AXMenuItem") return false;
  if (ax.subrole === "AXSeparatorMenuItem") return true;
  if (!ax.title && !ax.label && !ax.value && ax.frame && ax.frame.height <= 12) return true;
  return false;
}

/** Auto-generated AppKit identifiers (e.g. "_NS:9", "_NS:68") are unstable
 *  across sessions and should not be used for element targeting. */
function isAutoGeneratedId(id: string | undefined): boolean {
  return !!id && id.startsWith("_NS:");
}

/** Return identifier only if it's stable (not auto-generated). */
function stableIdentifier(id: string | undefined): string | undefined {
  return isAutoGeneratedId(id) ? undefined : id;
}

/** Detect AXStaticText nodes that are actually actionable buttons.
 *  Maps uses identifier="ButtonCellTitle" for Remove, Pin, Report actions. */
function isStaticTextButton(ax: AXNode): boolean {
  return ax.role === "AXStaticText" && ax.identifier === "ButtonCellTitle";
}

/** Convert an AXNode into a TreeNode, collapsing non-semantic containers. */
export function axToTree(ax: AXNode, siblingIndex = 0): TreeNode {
  const subroleTag = ax.subrole ? SUBROLE_TO_TAG[ax.subrole] : undefined;
  const isSearchTextField = ax.role === "AXTextField" && ax.subrole === "AXSearchField";
  const tag = isMenuSeparator(ax)
    ? "Separator"
    : isStaticTextButton(ax)
    ? "Button"
    : isSearchTextField
    ? "SearchField"
    : subroleTag || ROLE_TO_TAG[ax.role] || (ax.role ? ax.role.replace(/^AX/, "") : "Unknown");

  const props: Record<string, string> = {};
  if (ax.title) props.title = ax.title;
  if (ax.label && ax.label !== ax.title) props.label = ax.label;
  if (ax.value) props.value = ax.value;
  if (ax.identifier) props.identifier = ax.identifier;
  if (ax.placeholder) props.placeholder = ax.placeholder;

  const canonicalTag = ROLE_TO_TAG[ax.role];
  if (canonicalTag && tag !== canonicalTag) {
    props.axRole = ax.role;
  }

  if (ax.capabilities) {
    const caps = ax.capabilities;
    if (caps.selected) props.selected = "true";
    if (caps.checked) props.checked = "true";
    if (caps.expanded) props.expanded = "true";
    if (caps.focused) props.focused = "true";
    if (caps.enabled === false) props.enabled = "false";
    if (caps.canScroll) props.scroll = caps.scrollAxis || "both";
    if (caps.scrollValueV != null) props.scrollV = String(caps.scrollValueV);
    if (caps.scrollValueH != null) props.scrollH = String(caps.scrollValueH);
  }

  if (ax.frame) {
    props.frame = `(${Math.round(ax.frame.x)},${Math.round(ax.frame.y)},${Math.round(ax.frame.width)},${Math.round(ax.frame.height)})`;
  }

  const children = collectSemanticChildren(ax.children || [], tag);

  if ((tag === "Cell" || tag === "Row") && props.label && props.label.startsWith(",")) {
    const focusedField = children.find(
      (c) => c.tag === "TextField" && c.props.focused === "true" && c.props.value,
    );
    if (focusedField) {
      props.label = focusedField.props.value + props.label;
    }
  }

  const titleOrLabel = props.title || props.label || props.value || stableIdentifier(ax.identifier) || ax.placeholder || "";
  const id = `${tag}:${titleOrLabel}:${siblingIndex}`;

  if (tag === "MenuItem" && children.some(c => c.tag === "Menu")) {
    props.hasSubmenu = "true";
  }

  if (tag === "ScrollArea" && ax.capabilities?.canScroll) {
    const caps = ax.capabilities;
    const truncatedV = caps.scrollValueV != null && caps.scrollValueV < 0.99;
    const truncatedH = caps.scrollValueH != null && caps.scrollValueH < 0.99;
    if (truncatedV || truncatedH) {
      const dir = truncatedV ? "down" : "right";
      children.push({
        id: `More:${id}:0`,
        tag: "More",
        props: { direction: dir, scrollTarget: id },
        children: undefined,
      });
    }
  }

  return { id, tag, props, children: children.length > 0 ? children : undefined };
}

/** Tags whose children represent peer list items */
const LIST_LIKE_PARENTS = new Set(["List", "Table", "Outline", "ScrollArea", "Cell", "Row"]);

export function collectSemanticChildren(axChildren: AXNode[], parentTag?: string): TreeNode[] {
  const result: TreeNode[] = [];
  const tagCounts: Record<string, number> = {};

  for (const child of axChildren) {
    if (!child.role) continue;
    const subroleTag = child.subrole ? SUBROLE_TO_TAG[child.subrole] : undefined;
    const tag = subroleTag || ROLE_TO_TAG[child.role] || child.role.replace(/^AX/, "");
    if (SEMANTIC_TAGS.has(tag)) {
      const idx = tagCounts[tag] ?? 0;
      tagCounts[tag] = idx + 1;
      const node = axToTree(child, idx);
      if (node.tag === "MenuBar" && !node.children) continue;
      result.push(node);
    } else {
      const promoted = collectSemanticChildren(child.children || [], parentTag);
      for (const node of promoted) {
        const idx = tagCounts[node.tag] ?? 0;
        tagCounts[node.tag] = idx + 1;
        const reId = `${node.tag}:${node.props.title || node.props.label || node.props.value || stableIdentifier(node.props.identifier) || node.props.placeholder || ""}:${idx}`;
        result.push({ ...node, id: reId });
      }
    }
  }

  if (parentTag && LIST_LIKE_PARENTS.has(parentTag)) {
    const buttonCount = result.filter(n => n.tag === "Button").length;
    const staticCount = result.filter(n => n.tag === "StaticText").length;
    if (buttonCount > 0 && staticCount > 0 && buttonCount >= staticCount) {
      for (const node of result) {
        if (node.tag === "StaticText") {
          node.tag = "Button";
          const label = node.props.title || node.props.label || node.props.value || "";
          const idx = tagCounts["Button"] ?? 0;
          tagCounts["Button"] = idx + 1;
          node.id = `Button:${label}:${idx}`;
        }
      }
    }
  }

  return result;
}

/** Check if a MenuBarItem's dropdown is visually open. */
function isMenuOpen(menuBarItem: TreeNode): boolean {
  if (menuBarItem.props.selected === "true") return true;
  return false;
}

/** Convert a PlainNode (query engine output) to a NodeDescriptor (CRDT input).
 *  Uses per-type counters for stable IDs, matching the `n()` helper pattern. */
export function plainNodeToDescriptor(node: PlainNode, typeCounters = new Map<string, number>()): NodeDescriptor {
  const tag = node._tag;
  const typeIdx = typeCounters.get(tag) ?? 0;
  typeCounters.set(tag, typeIdx + 1);

  const attrs: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(node)) {
    if (k.startsWith("_")) continue; // skip _tag, _id, _children, _text, _displayName
    attrs[k] = v;
  }
  if (node._text) attrs.value = node._text;

  const name = (node._id as string) || attrs.label || attrs.title;
  const id = (typeof name === "string" && name)
    ? `${tag}:${name}:${typeIdx}`
    : `${tag}-${typeIdx}`;

  const children = node._children?.map(c => plainNodeToDescriptor(c, typeCounters));

  return {
    type: tag,
    id,
    attrs: Object.keys(attrs).length > 0 ? attrs : undefined,
    children: children && children.length > 0 ? children : undefined,
  };
}

export function treeNodeToDescriptor(node: TreeNode): NodeDescriptor {
  const attrs: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(node.props)) {
    attrs[key] = value;
  }

  let children: NodeDescriptor[] = [];
  if ((node.tag === "MenuBarItem" || node.tag === "MenuExtra") && !isMenuOpen(node)) {
    // Menu is closed — don't include dropdown children
  } else if (node.children) {
    children = node.children.map(treeNodeToDescriptor);
  }

  return {
    type: node.tag,
    id: node.id,
    attrs: Object.keys(attrs).length > 0 ? attrs : undefined,
    children: children.length > 0 ? children : undefined,
  };
}

function flattenDegenerateWindow(node: TreeNode): TreeNode {
  const children = node.children?.map(flattenDegenerateWindow);
  const current = children ? { ...node, children } : node;

  if (current.tag !== "Window" || current.children?.length !== 1) {
    return current;
  }

  const onlyChild = current.children[0];
  if (onlyChild.tag !== "Window") {
    return current;
  }

  return {
    ...onlyChild,
    id: onlyChild.id || current.id,
    props: {
      ...current.props,
      ...onlyChild.props,
    },
    children: onlyChild.children,
  };
}

/** Check if any menu is open from the raw AX menubar node. */
export function isAnyMenuOpenAX(menuBar: AXNode): boolean {
  if (!menuBar.children) return false;
  for (const mbi of menuBar.children) {
    if (mbi.role !== "AXMenuBarItem") continue;
    if (mbi.capabilities?.selected) return true;
  }
  return false;
}

export interface AXTreeResponse {
  app: string;
  bundleId: string;
  pid: number;
  frame?: { x: number; y: number; width: number; height: number };
  menuBar?: AXNode;
  tree?: AXNode;
}

interface WindowRect {
  pid: number;
  bundleId: string;
  x: number;
  y: number;
  w: number;
  h: number;
  title?: string;
}

export interface SnapshotResponse {
  schemaVersion: string;
  runningBundleIds?: string[];
  menuExtras?: { bundleId: string; items: AXNode[] }[];
  windowRects?: WindowRect[];
  focus: {
    frontmostBundleId: string;
    frontmostPid: number;
  };
  channels: {
    focused: {
      items: AXTreeResponse[];
    };
    visible?: {
      items: AXTreeResponse[];
    };
    menu?: {
      detected: boolean;
      item?: AXTreeResponse;
    };
  };
}

// Track high-water mark for screen dimensions
let stableScreenW = 0;
let stableScreenH = 0;

/** Reset screen dimensions (for testing). */
export function resetScreenDims() {
  stableScreenW = 0;
  stableScreenH = 0;
}

export function inferScreenDimensions(snap: SnapshotResponse): { w: number; h: number } {
  let w = 1440, h = 900;
  const menuBarItem = snap.channels?.focused?.items?.find(i => i.menuBar);
  if (menuBarItem?.menuBar?.frame) {
    w = Math.round(menuBarItem.menuBar.frame.width);
  }
  let maxBottom = 0;
  const front = snap.channels?.focused?.items?.[0];
  if (front?.frame) {
    maxBottom = Math.max(maxBottom, front.frame.y + front.frame.height);
  }
  if (maxBottom > 0) {
    h = maxBottom + 25;
  }
  stableScreenW = Math.max(stableScreenW, w);
  stableScreenH = Math.max(stableScreenH, h);
  return { w: stableScreenW, h: stableScreenH };
}

/** Build the full Display tree from a snapshot response. */
export function snapshotToTree(snap: SnapshotResponse): TreeNode | null {
  const items = snap.channels?.focused?.items;
  if (!items || items.length === 0) return null;

  const front = items[0];
  const menuBarSource = items.find(i => i.menuBar) || front;
  const systemChildren: TreeNode[] = [];

  // 1. Build MenuBar
  let menuBarNode: TreeNode | null = null;
  if (menuBarSource.menuBar) {
    const mb = axToTree(menuBarSource.menuBar);
    const mbChildren = mb.tag === "MenuBar" ? mb.children : [mb];
    if (mbChildren) {
      for (const child of mbChildren) {
        if (child.tag === "MenuBarItem") {
          child.props = { ...child.props, bundleId: front.bundleId };
        }
      }
    }
    menuBarNode = {
      id: "MenuBar::0",
      tag: "MenuBar",
      props: mb.props,
      children: mbChildren || [],
    };
  }

  // 2. MenuExtras
  if (snap.menuExtras?.length) {
    const extrasChildren: TreeNode[] = [];
    for (const group of snap.menuExtras) {
      for (let i = 0; i < group.items.length; i++) {
        const tree = axToTree(group.items[i], i);
        tree.tag = "MenuExtra";
        tree.id = tree.id.replace(/^MenuBarItem:/, "MenuExtra:");
        tree.props = { ...tree.props, bundleId: group.bundleId };
        extrasChildren.push(tree);
      }
    }
    systemChildren.push({
      id: "MenuExtras::0",
      tag: "MenuExtras",
      props: {},
      children: extrasChildren,
    });
  }

  // 3. Application with window
  if (front.tree) {
    const appNode = flattenDegenerateWindow(axToTree(front.tree));
    const appProps: Record<string, string> = { ...appNode.props };
    appProps.bundleId = front.bundleId;
    if (!appProps.title) appProps.title = front.app;

    let children = appNode.tag === "Application"
      ? (appNode.children || []).map(flattenDegenerateWindow)
      : [appNode];

    children = children.map((child) => {
      if (child.tag === "Window") {
        const wp = { ...child.props };
        // Use window's own AX frame if available, else fall back to front.frame
        const ownFrame = child.props.frame;
        if (ownFrame) {
          const m = ownFrame.match(/\((-?\d+),(-?\d+),(-?\d+),(-?\d+)\)/);
          if (m) {
            wp.x = m[1]; wp.y = m[2]; wp.w = m[3]; wp.h = m[4];
          }
        } else if (front.frame) {
          wp.x = String(Math.round(front.frame.x));
          wp.y = String(Math.round(front.frame.y));
          wp.w = String(Math.round(front.frame.width));
          wp.h = String(Math.round(front.frame.height));
        }
        return { ...child, props: wp };
      }
      return child;
    });

    // MenuBar is pushed to Display level (sibling of Application, like MenuExtras)
    if (menuBarNode) {
      systemChildren.push(menuBarNode);
    }

    systemChildren.push({
      id: `app:${front.bundleId}`,
      tag: "Application",
      props: appProps,
      children,
    });
  }

  const screenDims = inferScreenDimensions(snap);
  const systemProps: Record<string, string> = {
    screenW: String(screenDims.w),
    screenH: String(screenDims.h),
    frontApp: front.bundleId || "",
  };

  return {
    id: "Display::0",
    tag: "Display",
    props: systemProps,
    children: systemChildren,
  };
}
